## 13.1 æfingadæmi
Afritið forritið að ofan inn í vinnubók og keyrið það nokkrum sinnum. Breytið svo forritinu í fall, dragaspil() sem skilar streng með dregnu spili.

1. Búið í framhaldi til forrit sem dregur fimm spil, sem er einmitt fjöldi spila í pókerhönd. Athugið að hér er smá svindl í gangi því það verður möguleiki á að draga sama spil tvisvar. Í kafla 13.5 verður ráðin bót á því.

2. [Vinnist í samstarfi við kennara.] Búið til fall sem kannar hvort pókerhönd hafi tvær tvennur. Skrifið í famhaldi forrit sem finnur líkurnar á að fá tvær tvennur með hermun (þá eru dregnar margar hendur og athugað hve stórt hlutfall þeirra er hönd með tveim tvennum).

In [2]:
from random import shuffle

def has_two_pairs(hand):
    # Sort the hand by rank
    hand.sort(key=lambda x: x[0])
    
    # Check if there are two pairs
    pairs = 0
    for i in range(len(hand) - 1):
        if hand[i][0] == hand[i+1][0]:
            pairs += 1
    
    return pairs == 2

def simulate_two_pairs(num_hands):
    deck = [(rank, suit) for rank in range(2, 15) for suit in range(4)]
    num_two_pairs = 0
    
    for i in range(num_hands):
        # Shuffle the deck
        shuffle(deck)
        
        # Deal a five-card hand
        hand = deck[:5]
        
        # Check if the hand has two pairs
        if has_two_pairs(hand):
            num_two_pairs += 1
    
    # Calculate the probability of getting two pairs
    probability = num_two_pairs / num_hands
    return probability

# Example usage
num_hands = 1000000
probability = simulate_two_pairs(num_hands)
print(f"The probability of getting two pairs in a five-card hand is approximately {probability:.4f}")


The probability of getting two pairs in a five-card hand is approximately 0.0691


## 13.3 

Afritið sýnidæmið að framan inn í vinnubók og breytið því svo og dragið:

1. 4 \times 4 fylki með tölum úr stöðluðu normaldreifingunni, N(0,1)

2. vigur með 7 tölum í \{2,4,6,\ldots,100\}

3. 3 \times 3 fylki með tölum á bilinu [2,5] með rng.random

4. 3 \times 3 fylki með tölum á bilinu [2,5] með rng.uniform

Í lið 2 eru fyrst búnar til tölur í \{1,2,\ldots,50\} og niðurstaðan margfölduð með 2, og í lið 3 er fyrst búið til fylki með tölum í [0,1] og svo þarf að margfalda með 3 og leggja 2 við.

In [3]:
import numpy as np

# 4x4 array with numbers from standard normal distribution
a = np.random.randn(4, 4)

# vector with 7 even numbers from 2 to 100
b = np.arange(2, 101, 2)[:7]

# 3x3 array with random numbers from [2, 5]
c = np.random.random((3, 3)) * 3 + 2

# 3x3 array with uniform random numbers from [2, 5]
d = np.random.uniform(2, 5, (3, 3))

print(a)
print(b)
print(c)
print(d)


[[-0.28751991 -1.19855335 -0.87121237 -0.3893416 ]
 [-0.59940561  1.09194885 -0.34079312  0.34661254]
 [-0.01846205  0.3099828   0.86985051  1.42375377]
 [-0.31349665  0.48628    -0.81314949  0.14611577]]
[ 2  4  6  8 10 12 14]
[[2.41645304 4.56257472 2.43825701]
 [2.47206946 2.38970953 2.71495975]
 [3.7573134  2.29491246 4.20709508]]
[[3.31810076 3.8204354  3.52923033]
 [2.21463339 4.38729132 4.04318787]
 [4.19294494 2.6994723  2.63763692]]


## 13.4 

Prófið að keyra forritsbútinn hér á undan með öðru seed, og prófið líka að sleppa frumstillingunni


In [4]:
import numpy as np

np.random.seed(123)
x = np.random.randint(1, 10, size=5)
print(x)

np.random.seed(123)
y = np.random.randint(1, 10, size=5)
print(y)

np.random.seed()
z = np.random.randint(1, 10, size=5)
print(z)

[3 3 7 2 4]
[3 3 7 2 4]
[8 3 2 7 7]


## 13.5

In [5]:
import numpy as np
from random import sample

# Raða lista í handahófsröð
names = ["Ari", "Ása", "Jói", "Óli", "Una"]
shuffle(names)
print(names)

# Velja þrjá af handahófi
chosen = sample(names, 3)
print(chosen)

# Búa til vigur og raða í slembiröð
x = [k + k**2 for k in range(1, 6)]
y = np.array([x_k for x_k in x])
np.random.shuffle(y)
print(y)

# Raða spurningum og svörum í handahófsröð
questions = ["Litur himinsins?", "2+2?", "Hver vann?", "Er sól?"]
answers = ["blár", "4", "Jói", "nei"]
q_indices = sample(range(len(questions)), len(questions))
shuffled_questions = [questions[i] for i in q_indices]
shuffled_answers = [answers[i] for i in q_indices]
print(shuffled_questions)
print(shuffled_answers)


['Jói', 'Ari', 'Óli', 'Ása', 'Una']
['Óli', 'Ása', 'Una']
[12 20  6 30  2]
['Litur himinsins?', 'Er sól?', '2+2?', 'Hver vann?']
['blár', 'nei', '4', 'Jói']
